export const SKILL_PACK_TOOLS: Record<string, string[]> = {
  calendar_pack: ["add_calendar_event","read_calendar_events","update_calendar_event","delete_calendar_event","search_calendar_events","add_habit","update_habit","complete_habit_entry","undo_habit_entry","delete_habit","archive_habit","read_habit_tracker","view_habit_stats","suggest_weekly_plan","export_calendar_ics","create_shared_calendar","add_shared_calendar_member","add_shared_event","read_shared_events","delete_shared_event","send_shared_message","read_shared_chat","delete_shared_message","leave_shared_calendar","view_shared_members","notify_habit_progress","remind_shared_event"],
  chat_pack: ["send_message","read_unread_messages","read_full_conversation","create_study_group","add_group_member","view_group_members","edit_group_info","leave_group","search_user_by_name","edit_sent_message","delete_sent_message","broadcast_message","pin_important_message","react_with_emoji","mute_chat_notifications","report_chat_message","upload_chat_media","schedule_message","create_chat_poll","mention_user","search_chat_history","start_video_call","share_library_material","check_read_receipts","clear_chat_history"],
  library_pack: ["search_library","search_documents","query_repositories","view_own_library_items","delete_own_library_item","list_indexed_documents","delete_indexed_document","summarize_document","extract_questions_from_doc","cite_source","index_url_as_document","analyze_source_credibility","compare_two_documents","generate_table_of_contents","extract_text_from_image","generate_study_guide_from_docs","search_material_by_subject","share_document_with_friend","download_document_as_pdf","create_thematic_collection","translate_document","highlight_important_sections"],
  learning_pack: ["save_learned_concept","search_knowledge_graph","view_related_concepts","create_learning_path","detect_knowledge_gaps","spaced_repetition_review","generate_concept_map","view_progress_by_subject","connect_two_concepts","import_concepts_from_document","calculate_mastery_score","suggest_next_topic","generate_analogy","simplify_concept","generate_learning_insights"],
  content_pack: ["generate_document","generate_summary","create_study_plan","generate_presentation_outline","generate_essay","generate_glossary","generate_comparison_table","generate_code","generate_practice_questions","generate_mind_map","generate_bibliography","generate_project_template","generate_timeline","generate_formal_letter","generate_reading_sheet","generate_rubric","generate_research_report","generate_syllabus","generate_flashcards","create_exam","generate_creative_story","generate_debate_arguments"],
  media_pack: ["generate_image","search_image","generate_video","analyze_image","generate_mermaid_diagram","generate_podcast_script","describe_math_image","text_to_speech","transcribe_audio","generate_infographic_layout","generate_color_palette","extract_colors_from_image","resize_image","compress_image","generate_qr_code"],
  research_pack: ["search_web","browse_web_page","advanced_web_search","fact_check","search_wikipedia","compare_multiple_sources","deep_research","search_academic_paper","find_similar_papers","extract_paper_abstract","generate_literature_review","search_youtube_transcripts","search_news","translate_web_page","find_statistics","search_patents","get_stock_data","get_weather"],
  stats_pack: ["view_study_stats","generate_weekly_report","view_exam_history","analyze_strengths_weaknesses","view_habit_streaks","detect_procrastination","generate_academic_dashboard","view_activity_heatmap","analyze_time_distribution","predict_exam_score","calculate_gpa","export_stats_csv","generate_custom_chart","view_learning_velocity"],
  profile_pack: ["update_profile","update_avatar","send_friend_request","accept_friend_request","decline_friend_request","remove_friend","view_friends_list","search_users","view_user_profile","block_user","unblock_user","set_status_message","toggle_privacy_mode","generate_shareable_profile_card","view_badges_and_achievements","pin_achievement_to_profile","link_social_account"],
  edu_pack: ["graph_math_function","verify_calculus_solution","balance_chemical_equation","practice_language_vocabulary","solve_physics_problem","analyze_statistical_data","prepare_standardized_test","solve_programming_challenge","analyze_artwork","explain_scientific_phenomenon","language_speaking_practice","solve_multivariable_equation","review_essay_grammar","generate_historical_context","simulate_socratic_dialogue","explain_code_snippet","translate_ancient_text","identify_rhetorical_devices","generate_music_theory_exercise","simulate_business_case"],
};

export function resolveSkillPackTools(packs: string[]): string[] {
  return [...new Set(packs.flatMap((pack) => SKILL_PACK_TOOLS[pack] || []))];
}
