import { z } from "zod";
import { Skill, ToolDefinition } from "../../core/types";
import { createClient } from "@/utils/supabase/server";
import { findRelatedConcepts, linkConcepts, getGraphStats } from "@/lib/knowledge-graph";
import { getAIEmbedding, getAICompletion } from "@/lib/ai";

async function requireUser(context:any){if(!context?.userId)throw new Error("No user ID");const supabase=await createClient();return{supabase,userId:context.userId};}
async function docContent(documentId:string,userId:string){const {supabase}=await requireUser({userId});const {data,error}=await supabase.from("ai_document_chunks").select("content,chunk_index").eq("document_id",documentId).order("chunk_index").limit(50);if(error)throw error;return(data||[]).map(x=>x.content).join("\n\n");}

export const saveLearnedConceptTool:ToolDefinition={id:"save_learned_concept",category:"knowledge_graph",description:"Guardar un concepto real con embedding en el grafo del usuario.",risk:"write",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({title:z.string().min(1),description:z.string().optional(),subject:z.string().optional()}),execute:async(args,context)=>{try{const {supabase,userId}=await requireUser(context);const embedding=await getAIEmbedding(`Título: ${args.title}\nDescripción: ${args.description||""}`);const {data,error}=await supabase.from("knowledge_nodes").insert({user_id:userId,title:args.title,description:args.description||"",embedding:`[${embedding.join(",")}]`,source_type:args.subject||"chat_ia"}).select("id,title,description,source_type,created_at").single();if(error)throw error;return{success:true,message:`Concepto '${args.title}' guardado en el grafo.`,data}}catch(e:any){return{success:false,error:e.message}}}};

export const searchKnowledgeGraphTool:ToolDefinition={id:"search_knowledge_graph",category:"knowledge_graph",description:"Buscar conceptos reales semánticamente en el grafo.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({query:z.string().min(1)}),execute:async(args,context)=>{try{const {userId}=await requireUser(context);const concepts=await findRelatedConcepts(userId,args.query,10);return{success:true,message:`Encontré ${concepts.length} conceptos relacionados.`,data:{concepts}}}catch(e:any){return{success:false,error:e.message}}}};

export const viewRelatedConceptsTool:ToolDefinition={id:"view_related_concepts",category:"knowledge_graph",description:"Mostrar conceptos relacionados al nodo indicado.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({concept_id:z.string().min(1),limit:z.number().int().min(1).max(20).default(5)}),execute:async(args,context)=>{try{const {supabase,userId}=await requireUser(context);const {data:node,error}=await supabase.from("knowledge_nodes").select("id,title").eq("id",args.concept_id).eq("user_id",userId).single();if(error||!node)throw error||new Error("Concepto no encontrado");const concepts=await findRelatedConcepts(userId,node.title,args.limit);return{success:true,message:`Conceptos relacionados a ${node.title}.`,data:{center:node,concepts:concepts.filter((c:any)=>c.id!==node.id)}}}catch(e:any){return{success:false,error:e.message}}}};

export const createLearningPathTool:ToolDefinition={id:"create_learning_path",category:"knowledge_graph",description:"Construir ruta de aprendizaje usando conceptos reales y sus dependencias semánticas.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({subject:z.string().min(1)}),execute:async(args,context)=>{try{const {userId}=await requireUser(context);const known=await findRelatedConcepts(userId,args.subject,30);const prompt=`Crea una ruta de aprendizaje ordenada para ${args.subject}. Usa únicamente estos conceptos reales del estudiante: ${known.map((x:any)=>x.title).join(", ")}. Señala qué conoce y qué debe reforzar. No inventes resultados del usuario.`;const completion=await getAICompletion([{role:"user",content:prompt}],"gemini-3.6-flash");return{success:true,message:"Ruta de aprendizaje generada con el grafo real.",data:{knownConcepts:known,content:completion?.choices?.[0]?.message?.content||""}}}catch(e:any){return{success:false,error:e.message}}}};

export const detectKnowledgeGapsTool:ToolDefinition={id:"detect_knowledge_gaps",category:"knowledge_graph",description:"Detectar brechas usando el conocimiento real disponible y una evaluación del modelo.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({subject:z.string().min(1),expectedTopics:z.array(z.string()).optional()}),execute:async(args,context)=>{try{const {userId}=await requireUser(context);const known=await findRelatedConcepts(userId,args.subject,30);const expected=args.expectedTopics?.length?args.expectedTopics:[args.subject];const prompt=`Evalúa brechas de conocimiento para ${args.subject}. Conceptos reales guardados: ${known.map((x:any)=>x.title).join(", ")}. Temas esperados proporcionados: ${expected.join(", ")}. Distingue claramente evidencia disponible de inferencias; no inventes conceptos guardados.`;const completion=await getAICompletion([{role:"user",content:prompt}],"gemini-3.6-flash");return{success:true,message:"Brechas analizadas con datos reales.",data:{knownConcepts:known,expectedTopics:expected,analysis:completion?.choices?.[0]?.message?.content||""}}}catch(e:any){return{success:false,error:e.message}}}};

export const spacedRepetitionReviewTool:ToolDefinition={id:"spaced_repetition_review",category:"knowledge_graph",description:"Seleccionar conceptos antiguos o con menor confianza para repaso espaciado usando datos reales.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({days_since_review:z.number().int().min(1).max(365).default(7)}),execute:async({days_since_review},context)=>{try{const {supabase,userId}=await requireUser(context);const cutoff=new Date(Date.now()-days_since_review*86400000).toISOString();const {data,error}=await supabase.from("knowledge_nodes").select("id,title,description,confidence_level,last_reviewed_at,created_at").eq("user_id",userId).or(`last_reviewed_at.is.null,last_reviewed_at.lt.${cutoff}`).order("confidence_level",{ascending:true,nullsFirst:true}).limit(20);if(error)throw error;return{success:true,message:`Encontré ${data?.length||0} conceptos para repasar.`,data:{concepts:data||[],algorithm:"selección por fecha de revisión y confianza registrada"}}}catch(e:any){return{success:false,error:e.message}}}};

export const exportKnowledgeGraphTool:ToolDefinition={id:"export_knowledge_graph",category:"knowledge_graph",description:"Exportar nodos y relaciones reales del grafo.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({format:z.enum(["json","markdown","csv"]).default("json")}),execute:async({format},context)=>{try{const {supabase,userId}=await requireUser(context);const [{data:nodes,error:nError},{data:edges,error:eError}]=await Promise.all([supabase.from("knowledge_nodes").select("id,title,description,confidence_level,source_type,created_at,last_reviewed_at").eq("user_id",userId).order("created_at"),supabase.from("knowledge_edges").select("*").eq("user_id",userId)]);if(nError)throw nError;if(eError)throw eError;const graph={nodes:nodes||[],edges:edges||[]};if(format==="csv")return{success:true,message:"CSV del grafo generado.",data:{csv:["id,title,description,confidence_level,source_type",...(graph.nodes||[]).map((n:any)=>[n.id,JSON.stringify(n.title||""),JSON.stringify(n.description||""),n.confidence_level??"",n.source_type??""].join(","))].join("\n")}};if(format==="markdown")return{success:true,message:"Markdown del grafo generado.",data:{markdown:(nodes||[]).map((n:any)=>`- ${n.title}: ${n.description||""}`).join("\n")}};return{success:true,message:"Grafo exportado.",data:graph}}catch(e:any){return{success:false,error:e.message}}}};

export const generateConceptMapTool:ToolDefinition={id:"generate_concept_map",category:"knowledge_graph",description:"Generar mapa conceptual a partir de conceptos reales del grafo.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({topic:z.string().min(1)}),execute:async({topic},context)=>{try{const {userId}=await requireUser(context);const concepts=await findRelatedConcepts(userId,topic,15);const prompt=`Genera Mermaid válido para un mapa conceptual sobre ${topic} usando solo estos conceptos reales: ${concepts.map((x:any)=>x.title).join(", ")}. Devuelve solo Mermaid.`;const completion=await getAICompletion([{role:"user",content:prompt}],"gemini-3.6-flash");return{success:true,message:"Mapa conceptual generado.",data:{concepts,mermaid:completion?.choices?.[0]?.message?.content||""}}}catch(e:any){return{success:false,error:e.message}}}};

export const viewProgressBySubjectTool:ToolDefinition={id:"view_progress_by_subject",category:"knowledge_graph",description:"Consultar progreso real del grafo por materia.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({subject:z.string().optional()}),execute:async({subject},context)=>{try{const {supabase,userId}=await requireUser(context);let q=supabase.from("knowledge_nodes").select("id,title,confidence_level,source_type,created_at,last_reviewed_at").eq("user_id",userId);if(subject)q=q.or(`source_type.ilike.%${subject}%,title.ilike.%${subject}%`);const {data,error}=await q.limit(500);if(error)throw error;const items=data||[];const avg=items.length?items.reduce((a:number,n:any)=>a+Number(n.confidence_level||0),0)/items.length:0;return{success:true,message:`${items.length} conceptos encontrados.`,data:{subject:subject||null,concepts:items,count:items.length,averageConfidence:avg}}}catch(e:any){return{success:false,error:e.message}}}};

export const connectTwoConceptsTool:ToolDefinition={id:"connect_two_concepts",category:"knowledge_graph",description:"Crear una arista real entre dos conceptos del usuario.",risk:"write",requiresConfirmation:true,supportsAutopilot:false,schema:z.object({concept_a_id:z.string(),concept_b_id:z.string(),relationship:z.string().default("related_to")}),execute:async(args,context)=>{try{const {userId}=await requireUser(context);const success=await linkConcepts(userId,args.concept_a_id,args.concept_b_id,args.relationship);if(!success)throw new Error("No se pudo crear la relación.");return{success:true,message:"Relación creada en el grafo.",data:{conceptA:args.concept_a_id,conceptB:args.concept_b_id,relationship:args.relationship}}}catch(e:any){return{success:false,error:e.message}}}};

export const generateFlashcardsFromGraphTool:ToolDefinition={id:"generate_flashcards_from_graph",category:"knowledge_graph",description:"Generar flashcards basadas en conceptos reales del grafo.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({subject:z.string().min(1),count:z.number().int().min(1).max(20).default(10)}),execute:async({subject,count},context)=>{try{const {userId}=await requireUser(context);const concepts=await findRelatedConcepts(userId,subject,Math.min(count*2,30));const prompt=`Genera ${count} flashcards con pregunta y respuesta basadas únicamente en estos conceptos reales: ${concepts.map((x:any)=>`${x.title}: ${x.description||""}`).join(" | ")}. Devuelve JSON.`;const completion=await getAICompletion([{role:"user",content:prompt}],"gemini-3.6-flash");return{success:true,message:`Flashcards generadas desde ${concepts.length} conceptos reales.`,data:{concepts,content:completion?.choices?.[0]?.message?.content||""}}}catch(e:any){return{success:false,error:e.message}}}};

export const quizFromGraphTool:ToolDefinition={id:"quiz_from_graph",category:"knowledge_graph",description:"Crear quiz a partir de conceptos reales guardados.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({subject:z.string().min(1),count:z.number().int().min(1).max(10).default(5)}),execute:async({subject,count},context)=>{try{const {userId}=await requireUser(context);const concepts=await findRelatedConcepts(userId,subject,count*2);const prompt=`Crea ${count} preguntas de opción múltiple para ${subject} usando solo estos conceptos reales: ${concepts.map((x:any)=>x.title).join(", ")}. Devuelve JSON válido con question,options,answer.`;const completion=await getAICompletion([{role:"user",content:prompt}],"gemini-3.6-flash");return{success:true,message:"Quiz generado con el grafo real.",data:{concepts,content:completion?.choices?.[0]?.message?.content||""}}}catch(e:any){return{success:false,error:e.message}}}};

export const importConceptsFromDocTool:ToolDefinition={id:"import_concepts_from_document",category:"knowledge_graph",description:"Extraer conceptos desde un documento real y devolverlos para posterior guardado.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({document_id:z.string().uuid()}),execute:async({document_id},context)=>{try{const {userId}=await requireUser(context);const content=await docContent(document_id,userId);if(!content)throw new Error("El documento no tiene contenido indexado.");const completion=await getAICompletion([{role:"user",content:`Extrae hasta 10 conceptos importantes del siguiente documento. Devuelve JSON con title,description,subject. No inventes contenido.\n\n${content.slice(0,30000)}`}],"gemini-3.6-flash");return{success:true,message:"Conceptos extraídos del documento.",data:{documentId:document_id,content:completion?.choices?.[0]?.message?.content||""}}}catch(e:any){return{success:false,error:e.message}}}};

export const recommendNextTopicTool:ToolDefinition={id:"recommend_next_topic",category:"knowledge_graph",description:"Recomendar siguiente tema basándose en conceptos reales.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({subject:z.string().optional()}),execute:async({subject},context)=>{try{const {userId}=await requireUser(context);const concepts=await findRelatedConcepts(userId,subject||"aprendizaje",20);const prompt=`Recomienda el siguiente tema de estudio considerando estos conceptos reales del estudiante: ${concepts.map((x:any)=>x.title).join(", ")}. Materia solicitada: ${subject||"general"}. No inventes progreso.`;const completion=await getAICompletion([{role:"user",content:prompt}],"gemini-3.6-flash");return{success:true,message:"Recomendación generada desde el grafo real.",data:{concepts,recommendation:completion?.choices?.[0]?.message?.content||""}}}catch(e:any){return{success:false,error:e.message}}}};

export const calculateMasteryScoreTool:ToolDefinition={id:"calculate_mastery_score",category:"knowledge_graph",description:"Calcular dominio a partir de niveles de confianza reales.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({subject:z.string().min(1)}),execute:async({subject},context)=>{try{const {supabase,userId}=await requireUser(context);const {data,error}=await supabase.from("knowledge_nodes").select("confidence_level,source_type,title").eq("user_id",userId).or(`source_type.ilike.%${subject}%,title.ilike.%${subject}%`);if(error)throw error;const items=data||[];if(!items.length)return{success:false,error:`No hay conceptos registrados para ${subject}.`};const vals=items.map((n:any)=>Number(n.confidence_level||0));const max=Math.max(...vals,10);const score=Math.round(vals.reduce((a,b)=>a+b,0)/vals.length*10)/10;return{success:true,message:`Dominio estimado: ${score}/100 usando ${items.length} conceptos.`,data:{subject,score,maxObserved:max,conceptCount:items.length}}}catch(e:any){return{success:false,error:e.message}}}};

export const knowledgeGraphSkill:Skill={id:"knowledge-graph",name:"Aprendizaje y Knowledge Graph",category:"learning",description:"Memoria semántica y progreso de aprendizaje con datos reales.",tools:[saveLearnedConceptTool,searchKnowledgeGraphTool,viewRelatedConceptsTool,createLearningPathTool,detectKnowledgeGapsTool,spacedRepetitionReviewTool,exportKnowledgeGraphTool,generateConceptMapTool,viewProgressBySubjectTool,connectTwoConceptsTool,generateFlashcardsFromGraphTool,quizFromGraphTool,importConceptsFromDocTool,recommendNextTopicTool,calculateMasteryScoreTool]};
