import { z } from "zod";
import { Skill, ToolDefinition } from "../../core/types";
import { readCalendarEvents, updateCalendarEvent, deleteCalendarEvent, searchCalendarEvents, readHabitTracker, addHabitToTracker, updateHabit, completeHabitInTracker, undoHabitInTracker, deleteHabitFromTracker } from "@/actions/calendar";
import { createSharedCalendar, addCalendarMember, addSharedEvent, readSharedEvents, deleteSharedEvent, sendSharedMessage, readSharedChat, deleteSharedMessage, leaveSharedCalendar, getSharedCalendarMembers, notifySharedHabitProgress } from "@/actions/shared-calendars";

export const addCalendarEventTool: ToolDefinition = {
  id: "add_calendar_event", category: "calendar", description: "Crea un evento en el calendario personal. Solicita título, fecha/hora de inicio y fin. Detecta conflictos con eventos existentes.", risk: "write", requiresConfirmation: true, supportsAutopilot: false,
  schema: z.object({ title: z.string().min(1), description: z.string().optional(), date: z.string(), start_time: z.string().optional(), end_time: z.string().optional(), recurrence_rule: z.string().optional(), reminder_minutes: z.number().optional() }),
  execute: async (args) => {
    try {
      const { createClient } = await import("@/utils/supabase/server");
      const supabase = await createClient();
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return { success: false, error: "No autenticado" };
      const startISO = args.start_time ? `${args.date}T${args.start_time}:00` : `${args.date}T08:00:00`;
      const endISO = args.end_time ? `${args.date}T${args.end_time}:00` : `${args.date}T09:00:00`;
      const existing = await readCalendarEvents(args.date, args.date);
      const conflicts = existing.filter((e: any) => new Date(startISO).getTime() < new Date(e.end_time).getTime() && new Date(endISO).getTime() > new Date(e.start_time).getTime());
      const { data, error } = await supabase.from("calendar_events").insert({ user_id: user.id, title: args.title, description: args.description || null, start_time: startISO, end_time: endISO }).select().single();
      if (error) throw error;
      let message = `Evento "${args.title}" creado para el ${args.date}.`;
      if (conflicts.length > 0) message += ` ⚠️ Nota: hay ${conflicts.length} evento(s) en el mismo horario.`;
      return { success: true, message, data };
    } catch (e: any) { return { success: false, error: e.message || "Error al crear evento" }; }
  }
};

export const readCalendarTool: ToolDefinition = { id: "read_calendar", category: "calendar", description: "Lee los eventos del calendario en un rango de fechas.", risk: "read", requiresConfirmation: false, supportsAutopilot: true, schema: z.object({ startDate: z.string(), endDate: z.string() }), execute: async (args) => { try { const events = await readCalendarEvents(args.startDate, args.endDate); return { success: true, message: events.length ? `Se encontraron ${events.length} eventos entre ${args.startDate} y ${args.endDate}.` : `No hay eventos entre ${args.startDate} y ${args.endDate}.`, data: events }; } catch (error: any) { return { success: false, error: error.message || "Error al leer el calendario" }; } } };
export const updateCalendarEventTool: ToolDefinition = { id: "update_calendar_event", category: "calendar", description: "Edita un evento existente del calendario.", risk: "write", requiresConfirmation: true, supportsAutopilot: false, schema: z.object({ eventId: z.string(), title: z.string().optional(), description: z.string().optional(), start_time: z.string().optional(), end_time: z.string().optional() }), execute: async (args) => { try { await updateCalendarEvent(args.eventId, { title: args.title, description: args.description, start_time: args.start_time, end_time: args.end_time }); return { success: true, message: "Evento actualizado correctamente." }; } catch (error: any) { return { success: false, error: error.message || "Error al actualizar evento" }; } } };
export const deleteCalendarEventTool: ToolDefinition = { id: "delete_calendar_event", category: "calendar", description: "Elimina un evento del calendario personal permanentemente.", risk: "destructive", requiresConfirmation: true, supportsAutopilot: false, schema: z.object({ eventId: z.string() }), execute: async (args) => { try { await deleteCalendarEvent(args.eventId); return { success: true, message: "Evento eliminado correctamente." }; } catch (error: any) { return { success: false, error: error.message || "Error al eliminar evento" }; } } };
export const searchCalendarEventsTool: ToolDefinition = { id: "search_calendar_events", category: "calendar", description: "Busca eventos por palabra clave en título o descripción.", risk: "read", requiresConfirmation: false, supportsAutopilot: true, schema: z.object({ query: z.string().min(1) }), execute: async (args) => { try { const events = await searchCalendarEvents(args.query); return { success: true, message: `Se encontraron ${events.length} eventos con "${args.query}".`, data: events }; } catch (error: any) { return { success: false, error: error.message || "Error al buscar eventos" }; } } };
export const suggestWeeklyPlanTool: ToolDefinition = { id: "suggest_weekly_plan", category: "calendar", description: "Analiza hábitos y eventos de la semana y sugiere un horario optimizado para estudio, descanso y actividades.", risk: "read", requiresConfirmation: false, supportsAutopilot: true, schema: z.object({}), execute: async () => { try { const today = new Date(); const startOfWeek = new Date(today); startOfWeek.setDate(today.getDate() - today.getDay()); const endOfWeek = new Date(startOfWeek); endOfWeek.setDate(startOfWeek.getDate() + 6); const fmt = (d: Date) => d.toISOString().split("T")[0]; const events = await readCalendarEvents(fmt(startOfWeek), fmt(endOfWeek)); const habits = await readHabitTracker(fmt(startOfWeek)); return { success: true, message: "Datos obtenidos para planificación semanal.", data: { events, habits, instruction: "Genera un plan semanal optimizado basado en los eventos y hábitos del usuario. Incluye bloques de estudio, descanso y actividades. Formato: tabla Markdown con días y horarios." } }; } catch (e: any) { return { success: false, error: e.message || "Error al generar plan" }; } } };

export const addHabitTool: ToolDefinition = { id: "add_habit", category: "calendar", description: "Crea un nuevo hábito con nombre, frecuencia y hora objetivo.", risk: "write", requiresConfirmation: true, supportsAutopilot: false, schema: z.object({ title: z.string().min(1), frequency: z.string().optional(), target_time: z.string().optional() }), execute: async (args) => { try { const data = await addHabitToTracker(args.title, args.frequency, args.target_time); return { success: true, message: `Hábito "${args.title}" creado exitosamente. ¡A mantener la racha! 🔥`, data }; } catch (e: any) { return { success: false, error: e.message || "Error al crear hábito" }; } } };
export const readHabitsTool: ToolDefinition = { id: "read_habits", category: "calendar", description: "Muestra todos los hábitos activos, su racha actual, completados esta semana y porcentaje de cumplimiento.", risk: "read", requiresConfirmation: false, supportsAutopilot: true, schema: z.object({ weekStart: z.string().optional() }), execute: async (args) => { try { const habits = await readHabitTracker(args.weekStart); return { success: true, message: `Se encontraron ${habits.length} hábitos activos.`, data: habits }; } catch (error: any) { return { success: false, error: error.message || "Error al leer hábitos" }; } } };
export const completeHabitTool: ToolDefinition = { id: "complete_habit", category: "calendar", description: "Marca un hábito como completado para hoy o una fecha específica.", risk: "write", requiresConfirmation: false, supportsAutopilot: true, schema: z.object({ habitId: z.string(), date: z.string().optional() }), execute: async (args) => { try { const result = await completeHabitInTracker(args.habitId, args.date); return { success: true, message: `Hábito completado. Racha actual: ${result.streak} día(s). 🔥`, data: result }; } catch (e: any) { return { success: false, error: e.message || "Error al completar hábito" }; } } };
export const undoHabitTool: ToolDefinition = { id: "undo_habit", category: "calendar", description: "Deshace un completado de hábito.", risk: "write", requiresConfirmation: false, supportsAutopilot: true, schema: z.object({ habitId: z.string(), date: z.string().optional() }), execute: async (args) => { try { const result = await undoHabitInTracker(args.habitId, args.date); return { success: true, message: `Completado desmarcado. Racha actual: ${result.streak} día(s).`, data: result }; } catch (e: any) { return { success: false, error: e.message || "Error al deshacer hábito" }; } } };
export const updateHabitTool: ToolDefinition = { id: "update_habit", category: "calendar", description: "Cambia nombre, frecuencia u hora objetivo de un hábito sin perder historial.", risk: "write", requiresConfirmation: true, supportsAutopilot: false, schema: z.object({ habitId: z.string(), title: z.string().optional(), frequency: z.string().optional(), target_time: z.string().optional() }), execute: async (args) => { try { const data = await updateHabit(args.habitId, { ...(args.title !== undefined ? { title: args.title } : {}), ...(args.frequency !== undefined ? { frequency: args.frequency } : {}), ...(args.target_time !== undefined ? { target_time: args.target_time } : {}) }); return { success: true, message: "Hábito actualizado sin modificar su historial.", data }; } catch (e: any) { return { success: false, error: e.message || "Error al actualizar hábito" }; } } };
export const deleteHabitTool: ToolDefinition = { id: "delete_habit", category: "calendar", description: "Elimina un hábito permanentemente.", risk: "destructive", requiresConfirmation: true, supportsAutopilot: false, schema: z.object({ habitId: z.string() }), execute: async (args) => { try { const data = await deleteHabitFromTracker(args.habitId, false); return { success: true, message: "Hábito eliminado permanentemente.", data }; } catch (e: any) { return { success: false, error: e.message || "Error al eliminar hábito" }; } } };
export const archiveHabitTool: ToolDefinition = { id: "archive_habit", category: "calendar", description: "Archiva un hábito; su historial se conserva.", risk: "write", requiresConfirmation: true, supportsAutopilot: false, schema: z.object({ habitId: z.string() }), execute: async (args) => { try { const data = await deleteHabitFromTracker(args.habitId, true); return { success: true, message: "Hábito archivado; su historial se conserva.", data }; } catch (e: any) { return { success: false, error: e.message || "Error al archivar hábito" }; } } };
export const viewHabitStatsTool: ToolDefinition = { id: "view_habit_stats", category: "calendar", description: "Muestra estadísticas de hábitos.", risk: "read", requiresConfirmation: false, supportsAutopilot: true, schema: z.object({ habitId: z.string().optional() }), execute: async (args) => { try { const { getHabitStats } = await import("@/actions/calendar"); const stats = await getHabitStats(args.habitId); return { success: true, message: `Estadísticas calculadas para ${stats.length} hábito(s).`, data: stats }; } catch (e: any) { return { success: false, error: e.message || "Error al calcular estadísticas" }; } } };
export const exportCalendarIcsTool: ToolDefinition = { id: "export_calendar_ics", category: "calendar", description: "Genera un archivo .ics con todos los eventos del usuario (descargable).", risk: "read", requiresConfirmation: false, supportsAutopilot: true, schema: z.object({}), execute: async () => { try { const today = new Date(); const from = today.toISOString().slice(0, 10); const end = new Date(today); end.setFullYear(end.getFullYear() + 1); const events = await readCalendarEvents(from, end.toISOString().slice(0, 10)); const format = (v: string) => new Date(v).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z"); const esc = (v: any) => String(v ?? "").replace(/\\/g, "\\\\").replace(/;/g, "\\;").replace(/,/g, "\\,").replace(/\r?\n/g, "\\n"); const body = ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//Learn Up//Calendar//ES", ...events.flatMap((event: any) => ["BEGIN:VEVENT", `UID:${event.id}@learn-up`, `DTSTAMP:${format(event.created_at || event.start_time)}`, `DTSTART:${format(event.start_time)}`, `DTEND:${format(event.end_time)}`, `SUMMARY:${esc(event.title)}`, ...(event.description ? [`DESCRIPTION:${esc(event.description)}`] : []), "END:VEVENT"]), "END:VCALENDAR"].join("\r\n"); return { success: true, message: `Calendario exportado con ${events.length} evento(s).`, data: { filename: "learn-up-calendar.ics", content: body, mimeType: "text/calendar" } }; } catch (e: any) { return { success: false, error: e.message || "Error al exportar" }; } } };

export const createSharedCalendarTool: ToolDefinition = { id: "create_shared_calendar", category: "calendar", description: "Crea un calendario compartido con amigos.", risk: "write", requiresConfirmation: true, supportsAutopilot: false, schema: z.object({ name: z.string().min(1), description: z.string().optional() }), execute: async (args) => { try { const data = await createSharedCalendar(args.name, args.description); return { success: true, message: `Calendario compartido "${args.name}" creado.`, data }; } catch (e: any) { return { success: false, error: e.message || "Error al crear calendario compartido" }; } } };
export const addCalendarMemberTool: ToolDefinition = { id: "add_calendar_member", category: "calendar", description: "Añade un miembro a un calendario compartido.", risk: "write", requiresConfirmation: true, supportsAutopilot: false, schema: z.object({ calendar_id: z.string(), user_email: z.string().email() }), execute: async (args) => { try { const data = await addCalendarMember(args.calendar_id, args.user_email); return { success: true, message: "Miembro añadido al calendario compartido.", data }; } catch (e: any) { return { success: false, error: e.message || "Error al añadir miembro" }; } } };
export const addSharedEventTool: ToolDefinition = { id: "add_shared_event", category: "calendar", description: "Crea un evento en un calendario compartido.", risk: "write", requiresConfirmation: true, supportsAutopilot: false, schema: z.object({ calendar_id: z.string(), title: z.string().min(1), description: z.string().optional(), start_time: z.string(), end_time: z.string(), reminder_minutes: z.number().optional() }), execute: async (args) => { try { const data = await addSharedEvent(args.calendar_id, { title: args.title, description: args.description, start_time: args.start_time, end_time: args.end_time, reminder_minutes: args.reminder_minutes }); return { success: true, message: `Evento compartido "${args.title}" creado.`, data }; } catch (e: any) { return { success: false, error: e.message || "Error al crear evento compartido" }; } } };
export const readSharedEventsTool: ToolDefinition = { id: "read_shared_events", category: "calendar", description: "Lee eventos de un calendario compartido.", risk: "read", requiresConfirmation: false, supportsAutopilot: true, schema: z.object({ calendar_id: z.string(), start_date: z.string(), end_date: z.string() }), execute: async (args) => { try { const data = await readSharedEvents(args.calendar_id, args.start_date, args.end_date); return { success: true, message: `Se encontraron ${data.length} eventos compartidos.`, data }; } catch (e: any) { return { success: false, error: e.message || "Error al leer eventos compartidos" }; } } };
export const deleteSharedEventTool: ToolDefinition = { id: "delete_shared_event", category: "calendar", description: "Elimina un evento de un calendario compartido.", risk: "destructive", requiresConfirmation: true, supportsAutopilot: false, schema: z.object({ event_id: z.string() }), execute: async (args) => { try { await deleteSharedEvent(args.event_id); return { success: true, message: "Evento compartido eliminado." }; } catch (e: any) { return { success: false, error: e.message || "Error al eliminar evento compartido" }; } } };
export const sendSharedMessageTool: ToolDefinition = { id: "send_shared_message", category: "calendar", description: "Envía un mensaje en el chat de un calendario compartido.", risk: "write", requiresConfirmation: true, supportsAutopilot: false, schema: z.object({ calendar_id: z.string(), message: z.string().min(1) }), execute: async (args) => { try { const data = await sendSharedMessage(args.calendar_id, args.message); return { success: true, message: "Mensaje enviado al calendario compartido.", data }; } catch (e: any) { return { success: false, error: e.message || "Error al enviar mensaje" }; } } };
export const readSharedChatTool: ToolDefinition = { id: "read_shared_chat", category: "calendar", description: "Lee el chat de un calendario compartido.", risk: "read", requiresConfirmation: false, supportsAutopilot: true, schema: z.object({ calendar_id: z.string(), limit: z.number().int().min(1).max(100).optional() }), execute: async (args) => { try { const data = await readSharedChat(args.calendar_id, args.limit); return { success: true, message: `Se recuperaron ${data.length} mensajes.`, data }; } catch (e: any) { return { success: false, error: e.message || "Error al leer chat compartido" }; } } };
export const deleteSharedMessageTool: ToolDefinition = { id: "delete_shared_message", category: "calendar", description: "Elimina un mensaje propio del chat compartido.", risk: "destructive", requiresConfirmation: true, supportsAutopilot: false, schema: z.object({ message_id: z.string() }), execute: async (args) => { try { await deleteSharedMessage(args.message_id); return { success: true, message: "Mensaje eliminado." }; } catch (e: any) { return { success: false, error: e.message || "Error al eliminar mensaje" }; } } };
export const leaveSharedCalendarTool: ToolDefinition = { id: "leave_shared_calendar", category: "calendar", description: "Abandona un calendario compartido. El creador no puede salir; debe eliminarlo.", risk: "write", requiresConfirmation: true, supportsAutopilot: false, schema: z.object({ calendar_id: z.string() }), execute: async (args) => { try { await leaveSharedCalendar(args.calendar_id); return { success: true, message: "Has abandonado el calendario compartido." }; } catch (e: any) { return { success: false, error: e.message || "Error al abandonar calendario" }; } } };
export const getSharedCalendarMembersTool: ToolDefinition = { id: "view_shared_members", category: "calendar", description: "Lista miembros con rol y fecha de incorporación.", risk: "read", requiresConfirmation: false, supportsAutopilot: true, schema: z.object({ calendar_id: z.string() }), execute: async (args) => { try { const data = await getSharedCalendarMembers(args.calendar_id); return { success: true, message: `${data.length} miembro(s) encontrado(s).`, data }; } catch (e: any) { return { success: false, error: e.message || "Error al listar miembros" }; } } };
export const notifySharedHabitProgressTool: ToolDefinition = { id: "notify_shared_habit_progress", category: "calendar", description: "Comparte progreso de hábito con grupo con permiso.", risk: "write", requiresConfirmation: true, supportsAutopilot: false, schema: z.object({ habit_id: z.string(), calendar_id: z.string() }), execute: async (args) => { try { const data = await notifySharedHabitProgress(args.habit_id, args.calendar_id); return { success: true, message: "Progreso compartido.", data }; } catch (e: any) { return { success: false, error: e.message || "Error al compartir progreso" }; } } };

export const calendarSkill: Skill = { id: "calendar", name: "Calendario y Habit Tracker", category: "calendar", description: "Gestión de eventos, hábitos, recordatorios y calendarios compartidos.", tools: [addCalendarEventTool, readCalendarTool, updateCalendarEventTool, deleteCalendarEventTool, searchCalendarEventsTool, suggestWeeklyPlanTool, addHabitTool, readHabitsTool, completeHabitTool, undoHabitTool, updateHabitTool, deleteHabitTool, archiveHabitTool, viewHabitStatsTool, exportCalendarIcsTool, createSharedCalendarTool, addCalendarMemberTool, addSharedEventTool, readSharedEventsTool, deleteSharedEventTool, sendSharedMessageTool, readSharedChatTool, deleteSharedMessageTool, leaveSharedCalendarTool, getSharedCalendarMembersTool, notifySharedHabitProgressTool] };