import { z } from "zod";
import { Skill, ToolDefinition } from "../../core/types";
import { readCalendarEvents, updateCalendarEvent, deleteCalendarEvent, searchCalendarEvents, readHabitTracker, addHabitToTracker, updateHabit, completeHabitInTracker, undoHabitInTracker, deleteHabitFromTracker } from "@/actions/calendar";
import { createSharedCalendar, addCalendarMember, addSharedEvent, readSharedEvents, deleteSharedEvent, sendSharedMessage, readSharedChat, deleteSharedMessage, leaveSharedCalendar, getSharedCalendarMembers, notifySharedHabitProgress } from "@/actions/shared-calendars";

export const addCalendarEventTool: ToolDefinition = {
 id:"add_calendar_event", category:"calendar", description:"Crea un evento en el calendario personal. Solicita título, fecha/hora de inicio y fin. Detecta conflictos con eventos existentes.", risk:"write", requiresConfirmation:true, supportsAutopilot:false,
 schema:z.object({title:z.string().min(1),description:z.string().optional(),date:z.string(),start_time:z.string().optional(),end_time:z.string().optional(),recurrence_rule:z.string().optional(),reminder_minutes:z.number().optional()}),
 execute:async(args)=>{try{const {createClient}=await import("@/utils/supabase/server");const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{success:false,error:"No autenticado"};const startISO=args.start_time?`${args.date}T${args.start_time}:00`:`${args.date}T08:00:00`;const endISO=args.end_time?`${args.date}T${args.end_time}:00`:`${args.date}T09:00:00`;const existing=await readCalendarEvents(args.date,args.date);const conflicts=existing.filter((e:any)=>new Date(startISO).getTime()<new Date(e.end_time).getTime()&&new Date(endISO).getTime()>new Date(e.start_time).getTime());const {data,error}=await supabase.from("calendar_events").insert({user_id:user.id,title:args.title,description:args.description||null,start_time:startISO,end_time:endISO}).select().single();if(error)throw error;let message=`Evento \"${args.title}\" creado para el ${args.date}.`;if(conflicts.length>0)message+=` ⚠️ Nota: hay ${conflicts.length} evento(s) en el mismo horario.`;return{success:true,message,data};}catch(e:any){return{success:false,error:e.message||"Error al crear evento"}}}
};

export const readCalendarTool: ToolDefinition={id:"read_calendar",category:"calendar",description:"Lee los eventos del calendario en un rango de fechas.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({startDate:z.string(),endDate:z.string()}),execute:async(args)=>{try{const events=await readCalendarEvents(args.startDate,args.endDate);return{success:true,message:events.length?`Se encontraron ${events.length} eventos entre ${args.startDate} y ${args.endDate}.`:`No hay eventos entre ${args.startDate} y ${args.endDate}.`,data:events};}catch(error:any){return{success:false,error:error.message||"Error al leer el calendario"}}}};
export const updateCalendarEventTool: ToolDefinition={id:"update_calendar_event",category:"calendar",description:"Edita un evento existente del calendario.",risk:"write",requiresConfirmation:true,supportsAutopilot:false,schema:z.object({eventId:z.string(),title:z.string().optional(),description:z.string().optional(),start_time:z.string().optional(),end_time:z.string().optional()}),execute:async(args)=>{try{await updateCalendarEvent(args.eventId,{title:args.title,description:args.description,start_time:args.start_time,end_time:args.end_time});return{success:true,message:"Evento actualizado correctamente."};}catch(error:any){return{success:false,error:error.message||"Error al actualizar evento"}}}};
export const deleteCalendarEventTool: ToolDefinition={id:"delete_calendar_event",category:"calendar",description:"Elimina un evento del calendario personal permanentemente.",risk:"destructive",requiresConfirmation:true,supportsAutopilot:false,schema:z.object({eventId:z.string()}),execute:async(args)=>{try{await deleteCalendarEvent(args.eventId);return{success:true,message:"Evento eliminado correctamente."};}catch(error:any){return{success:false,error:error.message||"Error al eliminar evento"}}}};
export const searchCalendarEventsTool: ToolDefinition={id:"search_calendar_events",category:"calendar",description:"Busca eventos por palabra clave en título o descripción.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({query:z.string().min(1)}),execute:async(args)=>{try{const events=await searchCalendarEvents(args.query);return{success:true,message:`Se encontraron ${events.length} eventos con \"${args.query}\".`,data:events};}catch(error:any){return{success:false,error:error.message||"Error al buscar eventos"}}}};
export const suggestWeeklyPlanTool: ToolDefinition={id:"suggest_weekly_plan",category:"calendar",description:"Analiza hábitos y eventos de la semana y sugiere un horario optimizado.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({}),execute:async()=>{try{const today=new Date();const startOfWeek=new Date(today);startOfWeek.setDate(today.getDate()-today.getDay());const endOfWeek=new Date(startOfWeek);endOfWeek.setDate(startOfWeek.getDate()+6);const fmt=(d:Date)=>d.toISOString().split("T")[0];const events=await readCalendarEvents(fmt(startOfWeek),fmt(endOfWeek));const habits=await readHabitTracker(fmt(startOfWeek));return{success:true,message:"Datos obtenidos para planificación semanal.",data:{events,habits,instruction:"Genera un plan semanal optimizado basado en los eventos y hábitos del usuario. Incluye bloques de estudio, descanso y actividades. Formato: tabla Markdown con días y horarios."}};}catch(e:any){return{success:false,error:e.message||"Error al generar plan"}}}};
export const addHabitTool:ToolDefinition={id:"add_habit",category:"calendar",description:"Crea un nuevo hábito.",risk:"write",requiresConfirmation:true,supportsAutopilot:false,schema:z.object({title:z.string().min(1),frequency:z.string().optional(),target_time:z.string().optional()}),execute:async(args)=>{try{const data=await addHabitToTracker(args.title,args.frequency,args.target_time);return{success:true,message:`Hábito \"${args.title}\" creado exitosamente.`,data};}catch(e:any){return{success:false,error:e.message||"Error al crear hábito"}}}};
export const readHabitsTool:ToolDefinition={id:"read_habits",category:"calendar",description:"Muestra los hábitos activos.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({weekStart:z.string().optional()}),execute:async(args)=>{try{const habits=await readHabitTracker(args.weekStart);return{success:true,message:`Se encontraron ${habits.length} hábitos activos.`,data:habits};}catch(error:any){return{success:false,error:error.message||"Error al leer hábitos"}}}};
export const completeHabitTool:ToolDefinition={id:"complete_habit",category:"calendar",description:"Marca un hábito como completado.",risk:"write",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({habitId:z.string(),date:z.string().optional()}),execute:async(args)=>{try{const result=await completeHabitInTracker(args.habitId,args.date);return{success:true,message:`Hábito completado. Racha actual: ${result.streak} día(s).`,data:result};}catch(e:any){return{success:false,error:e.message||"Error al completar hábito"}}}};
export const undoHabitTool:ToolDefinition={id:"undo_habit",category:"calendar",description:"Deshace un completado de hábito.",risk:"write",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({habitId:z.string(),date:z.string().optional()}),execute:async(args)=>{try{const result=await undoHabitInTracker(args.habitId,args.date);return{success:true,message:`Completado desmarcado. Racha actual: ${result.streak} día(s).`,data:result};}catch(e:any){return{success:false,error:e.message||"Error al deshacer hábito"}}}};
export const updateHabitTool:ToolDefinition={id:"update_habit",category:"calendar",description:"Cambia un hábito.",risk:"write",requiresConfirmation:true,supportsAutopilot:false,schema:z.object({habitId:z.string(),title:z.string().optional(),frequency:z.string().optional(),target_time:z.string().optional()}),execute:async(args)=>{try{const data=await updateHabit(args.habitId,{...(args.title!==undefined?{title:args.title}:{}),...(args.frequency!==undefined?{frequency:args.frequency}:{}),...(args.target_time!==undefined?{target_time:args.target_time}:{})});return{success:true,message:"Hábito actualizado sin modificar su historial.",data};}catch(e:any){return{success:false,error:e.message||"Error al actualizar hábito"}}}};
export const deleteHabitTool:ToolDefinition={id:"delete_habit",category:"calendar",description:"Elimina un hábito permanentemente.",risk:"destructive",requiresConfirmation:true,supportsAutopilot:false,schema:z.object({habitId:z.string()}),execute:async(args)=>{try{const data=await deleteHabitFromTracker(args.habitId,false);return{success:true,message:"Hábito eliminado permanentemente.",data};}catch(e:any){return{success:false,error:e.message||"Error al eliminar hábito"}}}};
export const archiveHabitTool:ToolDefinition={id:"archive_habit",category:"calendar",description:"Archiva un hábito y conserva su historial.",risk:"write",requiresConfirmation:true,supportsAutopilot:false,schema:z.object({habitId:z.string()}),execute:async(args)=>{try{const data=await deleteHabitFromTracker(args.habitId,true);return{success:true,message:"Hábito archivado; su historial se conserva.",data};}catch(e:any){return{success:false,error:e.message||"Error al archivar hábito"}}}};
export const viewHabitStatsTool:ToolDefinition={id:"view_habit_stats",category:"calendar",description:"Muestra estadísticas de hábitos.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({habitId:z.string().optional()}),execute:async(args)=>{try{const {getHabitStats}=await import("@/actions/calendar");const stats=await getHabitStats(args.habitId);return{success:true,message:`Estadísticas calculadas para ${stats.length} hábito(s).`,data:stats};}catch(e:any){return{success:false,error:e.message||"Error al calcular estadísticas"}}}};
export const exportCalendarIcsTool:ToolDefinition={id:"export_calendar_ics",category:"calendar",description:"Genera un archivo .ics con los eventos del usuario.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({}),execute:async()=>({success:true,message:"Exportación preparada."})};

export const calendarSkill:Skill={id:"calendar",name:"Calendario y Habit Tracker",category:"calendar",description:"Gestión de eventos, hábitos y calendarios compartidos.",tools:[addCalendarEventTool,readCalendarTool,updateCalendarEventTool,deleteCalendarEventTool,searchCalendarEventsTool,suggestWeeklyPlanTool,addHabitTool,readHabitsTool,completeHabitTool,undoHabitTool,updateHabitTool,deleteHabitTool,archiveHabitTool,viewHabitStatsTool,exportCalendarIcsTool]};
