import { z } from "zod";
import type { Skill, ToolDefinition } from "../../core/types";

async function generate(prompt:string,title:string){const {getAICompletion}=await import("@/lib/ai");const result=await getAICompletion([{role:"user",content:prompt}],"gemini-3.6-flash");const content=result?.choices?.[0]?.message?.content||"";if(!content.trim())return{success:false,error:`No se pudo generar ${title}.`};return{success:true,message:`${title} generado.`,data:{title,content,provider:"gemini-3.6-flash"}};}

export const generateStudyGuideTool:ToolDefinition={id:"generate_study_guide",category:"content",description:"Generar guía de estudio completa con introducción, secciones, ejemplos, resumen y práctica.",risk:"write",requiresConfirmation:true,supportsAutopilot:false,schema:z.object({topic:z.string().min(1),source_text:z.string().optional()}),execute:async({topic,source_text})=>generate(`Genera una guía de estudio completa sobre ${topic}. Incluye introducción, secciones temáticas, ejemplos resueltos, resumen y preguntas de práctica. Si se proporciona texto fuente, usa exclusivamente ese contenido para los hechos. Texto fuente: ${source_text||"No proporcionado."}`,`Guía de estudio: ${topic}`)};

export const generateExecutiveSummaryTool:ToolDefinition={id:"generate_summary",category:"content",description:"Resumen ejecutivo de 200 a 500 palabras.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({text:z.string().optional(),topic:z.string().optional(),max_words:z.number().int().min(50).max(1000).default(300)}),execute:async({text,topic,max_words})=>generate(`Crea un resumen ejecutivo de máximo ${max_words} palabras sobre ${topic||"el texto"}. No inventes datos. Si hay texto fuente, usa únicamente ese texto:\n${text||""}`,"Resumen ejecutivo")};

export const createStudyPlanTool:ToolDefinition={id:"create_study_plan",category:"content",description:"Crear plan de estudio personalizado con cronograma.",risk:"write",requiresConfirmation:true,supportsAutopilot:false,schema:z.object({subject:z.string().min(1),exam_date:z.string().optional(),hours_per_day:z.number().positive().default(2)}),execute:async({subject,exam_date,hours_per_day})=>generate(`Crea un plan de estudio personalizado para ${subject}. Fecha del examen: ${exam_date||"no indicada"}. Horas disponibles por día: ${hours_per_day}. Devuelve un cronograma semanal detallado con temas y actividades. No inventes una fecha si no se proporciona.`,`Plan de estudio: ${subject}`)};

export const generatePresentationOutlineTool:ToolDefinition={id:"generate_presentation_outline",category:"content",description:"Crear estructura de presentación por diapositivas.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({topic:z.string().min(1),slides:z.number().int().min(1).max(50).default(10)}),execute:async({topic,slides})=>generate(`Crea una estructura de ${slides} diapositivas sobre ${topic}. Para cada diapositiva incluye título, subtemas, puntos clave y sugerencias visuales.`,`Presentación: ${topic}`)};

export const generateEssayTool:ToolDefinition={id:"generate_essay",category:"content",description:"Generar ensayo académico estructurado.",risk:"write",requiresConfirmation:true,supportsAutopilot:false,schema:z.object({topic:z.string().min(1),format:z.enum(["APA","MLA","Chicago"]).default("APA"),word_count:z.number().int().min(200).max(10000).default(800)}),execute:async({topic,format,word_count})=>generate(`Escribe un ensayo académico de aproximadamente ${word_count} palabras sobre ${topic}, con introducción, desarrollo argumentativo y conclusión. Formato de referencias: ${format}. No inventes citas textuales ni fuentes; si no se proporcionan fuentes, indica que las referencias deben verificarse.`,`Ensayo: ${topic}`)};

export const generateAbstractTool:ToolDefinition={id:"generate_abstract",category:"content",description:"Generar abstract académico en español e inglés de máximo 250 palabras.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({text:z.string().min(1),language:z.enum(["es","en","both"]).default("both")}),execute:async({text,language})=>generate(`Genera un abstract académico de máximo 250 palabras a partir exclusivamente del texto proporcionado. Incluye objetivo, metodología, resultados y conclusiones sin inventar información. Idioma: ${language}.\n\n${text}`,"Abstract académico")};

export const generateGlossaryTool:ToolDefinition={id:"generate_glossary",category:"content",description:"Crear glosario alfabético con definiciones y ejemplos.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({topic:z.string().min(1),source_text:z.string().optional()}),execute:async({topic,source_text})=>generate(`Crea un glosario alfabético sobre ${topic}. Cada entrada debe tener definición clara y ejemplo. Si existe texto fuente, usa solo sus hechos.\n\n${source_text||""}`,`Glosario: ${topic}`)};

export const generateComparisonTableTool:ToolDefinition={id:"generate_comparison_table",category:"content",description:"Crear tabla comparativa de múltiples elementos.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({items:z.array(z.string()).min(2),dimensions:z.array(z.string()).optional()}),execute:async({items,dimensions})=>generate(`Compara ${items.join(", ")} en una tabla. Dimensiones: ${(dimensions||["definición","características","ventajas","limitaciones"]).join(", ")}. No inventes datos específicos sin respaldo en el contexto proporcionado.`,`Tabla comparativa`)};

export const generateCodeTool:ToolDefinition={id:"generate_code",category:"content",description:"Crear código funcional con comentarios y casos de prueba.",risk:"write",requiresConfirmation:true,supportsAutopilot:false,schema:z.object({language:z.string().min(1),description:z.string().min(1)}),execute:async({language,description})=>generate(`Escribe código funcional en ${language} para ${description}. Incluye comentarios claros, manejo razonable de errores y al menos un caso de prueba o ejemplo de uso.`,`Código: ${language}`)};

export const generateInfographicTextTool:ToolDefinition={id:"generate_infographic_text",category:"content",description:"Crear estructura de infografía en texto sin inventar estadísticas.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({topic:z.string().min(1),provided_stats:z.array(z.string()).optional()}),execute:async({topic,provided_stats})=>generate(`Diseña una infografía textual sobre ${topic}. Incluye encabezado, secciones, elementos visuales sugeridos y conclusiones. Solo usa estadísticas proporcionadas explícitamente: ${(provided_stats||[]).join(" | ")}. Toda cifra no proporcionada debe marcarse como "requiere fuente".`,`Infografía: ${topic}`)};

export const generatePracticeQuestionsTool:ToolDefinition={id:"generate_practice_questions",category:"content",description:"Crear preguntas de práctica con respuestas modelo.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({topic:z.string().min(1),count:z.number().int().min(5).max(20).default(10),type:z.enum(["conceptual","application","critical","mixed"]).default("mixed")}),execute:async({topic,count,type})=>generate(`Genera ${count} preguntas de práctica sobre ${topic}, tipo ${type}. Incluye respuestas modelo al final.`,`Preguntas de práctica: ${topic}`)};

export const generateMindMapTool:ToolDefinition={id:"generate_mind_map",category:"content",description:"Crear mapa mental en Mermaid o Markdown anidado.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({topic:z.string().min(1)}),execute:async({topic})=>generate(`Crea un mapa mental renderizable sobre ${topic} usando Mermaid mindmap o graph TD. Devuelve sintaxis Mermaid válida sin cercas de código.`,`Mapa mental: ${topic}`)};

export const generateBibliographyTool:ToolDefinition={id:"generate_bibliography",category:"content",description:"Formatear bibliografía a partir de fuentes proporcionadas.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({sources:z.array(z.any()).min(1),format:z.enum(["APA 7","MLA 9","Chicago","IEEE"]).default("APA 7")}),execute:async({sources,format})=>generate(`Formatea exclusivamente las siguientes fuentes reales en ${format}. No agregues fuentes que no aparezcan en los datos proporcionados.\n${JSON.stringify(sources)}`,`Bibliografía ${format}`)};

export const generateProjectTemplateTool:ToolDefinition={id:"generate_project_template",category:"content",description:"Crear plantilla completa de proyecto escolar o universitario.",risk:"write",requiresConfirmation:true,supportsAutopilot:false,schema:z.object({topic:z.string().min(1)}),execute:async({topic})=>generate(`Crea una plantilla completa para un proyecto académico sobre ${topic}: portada, índice, introducción, marco teórico, metodología, resultados, discusión, conclusiones y bibliografía.`,`Plantilla de proyecto: ${topic}`)};

export const generateTimelineTool:ToolDefinition={id:"generate_timeline",category:"content",description:"Generar línea de tiempo histórica estructurada.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({topic:z.string().min(1),period:z.string().optional()}),execute:async({topic,period})=>generate(`Genera una línea de tiempo estructurada sobre ${topic}. Período: ${period||"no especificado"}. Usa fechas solo cuando sean conocidas o estén en el material proporcionado.`,`Línea de tiempo: ${topic}`)};

export const generateFormalLetterTool:ToolDefinition={id:"generate_formal_letter",category:"content",description:"Redactar carta formal o informal según destinatario y propósito.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({purpose:z.string().min(1),recipient:z.string().min(1),tone:z.string().default("formal")}),execute:async({purpose,recipient,tone})=>generate(`Redacta una carta ${tone} para ${recipient}. Propósito: ${purpose}.`,`Carta para ${recipient}`)};

export const generateReadingSheetTool:ToolDefinition={id:"generate_reading_sheet",category:"content",description:"Crear ficha de lectura con autor, tesis, argumentos, citas y valoración crítica.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({text:z.string().min(1),author:z.string().optional()}),execute:async({text,author})=>generate(`Crea una ficha de lectura a partir exclusivamente del texto proporcionado${author?` y atribuido a ${author}`:""}. Incluye autor/año si aparecen, tesis central, argumentos, citas relevantes sin inventarlas y valoración crítica.\n${text}`,"Ficha de lectura")};

export const generateCollaborativeQuestionnaireTool:ToolDefinition={id:"generate_collaborative_questionnaire",category:"content",description:"Crear banco de preguntas para compartir con un grupo de estudio.",risk:"write",requiresConfirmation:true,supportsAutopilot:false,schema:z.object({topic:z.string().min(1),count:z.number().int().min(1).max(50).default(10)}),execute:async({topic,count})=>generate(`Crea un cuestionario colaborativo de ${count} preguntas sobre ${topic}, con opciones cuando corresponda y clave de respuestas separada para el docente.`,`Cuestionario colaborativo: ${topic}`)};

export const generateProjectScheduleTool:ToolDefinition={id:"generate_project_schedule",category:"content",description:"Crear cronograma de proyecto y diagrama de Gantt en Markdown o CSV.",risk:"write",requiresConfirmation:true,supportsAutopilot:false,schema:z.object({project:z.string().min(1),tasks:z.array(z.object({name:z.string(),duration_days:z.number().int().min(1)})).min(1)}),execute:async({project,tasks})=>generate(`Genera un cronograma de proyecto para ${project} usando exactamente estas tareas y duraciones: ${JSON.stringify(tasks)}. Incluye tabla y diagrama de Gantt en Markdown/Mermaid.`,`Cronograma: ${project}`)};

export const generateEvaluationFormTool:ToolDefinition={id:"generate_evaluation_form",category:"content",description:"Crear rúbrica de evaluación con cuatro niveles y puntajes.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({activity:z.string().min(1),criteria:z.array(z.string()).optional()}),execute:async({activity,criteria})=>generate(`Crea una rúbrica de evaluación para ${activity} con 4 niveles de desempeño, criterios claros y puntajes. Criterios proporcionados: ${(criteria||[]).join(", ")}.`,`Rúbrica: ${activity}`)};

export const generateResearchReportTool:ToolDefinition={id:"generate_research_report",category:"content",description:"Crear reporte académico usando fuentes web reales y documentos propios.",risk:"write",requiresConfirmation:true,supportsAutopilot:false,schema:z.object({topic:z.string().min(1),source_urls:z.array(z.string().url()).optional()}),execute:async({topic,source_urls})=>({success:true,message:"El reporte será ejecutado mediante el flujo de investigación con fuentes trazables.",data:{researchTopic:topic,source_urls:source_urls||[]}})};

export const generateSyllabusTool:ToolDefinition={id:"generate_syllabus",category:"content",description:"Crear syllabus detallado por semanas.",risk:"read",requiresConfirmation:false,supportsAutopilot:true,schema:z.object({subject:z.string().min(1),weeks:z.number().int().min(1).max(52).default(16)}),execute:async({subject,weeks})=>generate(`Crea un syllabus de ${subject} para ${weeks} semanas con objetivos, temas, actividades, evaluaciones y bibliografía sugerida claramente marcada para verificar.`,`Syllabus: ${subject}`)};

export const contentSkill:Skill={id:"content_generation",name:"Generación de Contenido",category:"content",description:"Las 22 herramientas de generación definidas por la especificación Learn Up.",tools:[generateStudyGuideTool,generateExecutiveSummaryTool,createStudyPlanTool,generatePresentationOutlineTool,generateEssayTool,generateAbstractTool,generateGlossaryTool,generateComparisonTableTool,generateCodeTool,generateInfographicTextTool,generatePracticeQuestionsTool,generateMindMapTool,generateBibliographyTool,generateProjectTemplateTool,generateTimelineTool,generateFormalLetterTool,generateReadingSheetTool,generateCollaborativeQuestionnaireTool,generateProjectScheduleTool,generateEvaluationFormTool,generateResearchReportTool,generateSyllabusTool]};
